De-cal/6-Snack-BE

.env.example

- env.example 업데이트가 되어있지 않아서 업데이트 해드렸습니다.
-
-

chore: env.example 추가

---

package-lock.json
package.json
prisma/migrations/20250709022559_add_unique_constraint/migration.sql
prisma/migrations/20250709023814_add_hashed_refresh_token_field_in_user_table/migration.sql
prisma/schema.prisma

- 장바구니 로직에 upsert를 사용하기 위해서 unique 제약 조건 추가 후 마이그레이션 했습니다.
-
-

chore: 스키마 CartItem에 Unique 제약조건 추가 [이태빈]

---

prisma/migrations/20250709025210_add_approver_field_in_order_table/migration.sql
prisma/mocks/order.mock.ts
prisma/schema.prisma

- Order 스키마에 approver 추가했습니다.
-
-

chore: Order 스키마에 approver 추가 [이태빈]

---

http/auth.http
http/order.http
src/controllers/order.controller.ts
src/dtos/order.dto.ts
src/repositories/order.repository.ts
src/routes/adminOrder.route.ts
src/routes/index.route.ts
src/services/order.service.ts
src/types/order.types.ts

- admin이 사용할 수 있는 승인된 주문 내역에 관련된 API 기능을 개발했습니다.
- 인증 미들웨어를 사용해서, 로그인 한 사용자인지 판단합니다.
- 유저 역할 미들웨어를 사용해서, 유저가 관리자 또는 최고관리자인지 판단합니다.
- 인가가 완료되면 관리자는 승인된 주문 내역의 리스트, 상세 내역을 조회할 수 있습니다.
-

feat: admin-order 작업 완료 [이태빈]

---

http/auth.http
http/budget.http
src/controllers/budget.controller.ts
src/dtos/budget.dto.ts
src/middlewares/validatedBudgetBody.middleware.ts
src/repositories/budget.repository.ts
src/routes/index.route.ts
src/routes/superAdmin.route.ts
src/routes/superAdminBudget.route.ts
src/services/budget.service.ts
src/types/budget.type.ts
src/utils/parseNumberOrThrow.ts

- 최고 관리자가 예산을 수정할 수 있는 API를 개발했습니다.
- 이번 달 예산과, 매달 시작 예산을 최고 관리자만 수정이 가능하도록 만들었습니다.
-

feat: 최고 관리자 예산 수정 API 완성 [이태빈]

---

http/auth.http
http/order.http
src/controllers/order.controller.ts
src/dtos/order.dto.ts
src/middlewares/validateGetOrderQuery.middleware.ts
src/middlewares/validateUpdateStatusOrderBody.middleware.ts
src/repositories/order.repository.ts
src/routes/adminOrder.route.ts
src/services/order.service.ts
src/types/order.types.ts

-
- 구매 요청 내역(PENDING) 조회와 상세 조회 할 수 있는 API 개발 완성했습니다.
-

feat/구매 요청 내역(PENDING) 조회, 상세 조회 API 개발 완성 [이태빈]

---

src/services/order.service.ts

- order에서 utils 함수를 잘못 임포트 해오고 있던 것을 수정했습니다.
-
-

fix: utils 함수 임포트 오류 수정 [이태빈]

---

http/product.http
src/controllers/product.controller.ts
src/repositories/product.repository.ts
src/routes/product.route.ts
src/services/product.service.ts
src/types/product.types.ts

- category Api 추가
- 기존에 있던 레포지토리에 카테고리를 검사하는 것과 다른 역할이라 따로 하나 더 만들고 서비스에서 가공했습니다.
-

feat: category Api 추가 [김우주]

---

http/auth.http
package-lock.json
package.json
src/app.ts
src/controllers/auth.controller.ts
src/controllers/user.controller.ts
src/repositories/user.repository.ts
src/routes/auth.route.ts
src/routes/user.route.ts
src/services/user.service.ts

-  프론트엔드에서 백엔드로 API 요청시 CORS 오류로 인해 요청-응답 과정이 원활하지 않아 오류가 발생해, 백엔드 프로젝트에서 CORS 설치하고 미들웨어 등록해야 합니다.
- CORS 라이브러리 package.json에 추가되고 App.ts에서 미들웨어 등록되었습니다.
- 프론트엔드에서 요청시 CORS 오류 없이 제대로 수행되면 목표 달성입니다.
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 …

feat: 내 정보 조회 API 추가 및 장바구니 개수 조회 기능 구현; cors 등록(https); [김홍섭]

---

http/order.http
package-lock.json

- npm i 명령어를 입력했을 때 보안에 취약한 패키지가 한 개 있다고 하여서 multer 업데이트 진행했습니다.(multer가 주 원인)
-
-

chore: 패키지 취약점 보완(multer 업데이트) [이태빈]

---

src/services/user.service.ts

- 회사 유저 목록 조회 기능 api에서, getUsersByCompany란 함수가 Service단에서 유저한테 받은 쿼리스트링을 숫자로 변환하여 respository에서 유저 리스트 조회시 오류가 나지 않게 설정하였습니다.
-
-

fix: 유저 목록조회 쿼리 숫자로 형변환되게 설정 [이지수B]

---

src/repositories/product.repository.ts

- 상품상세 페이지에서 상품의 대분류를 조회
- findProductById함수를 변경 
-

fix:상품상세 페이지에서 상품의 대분류를 조회하기위해 findProductById함수를 변경하였습니다 [조성빈]

---

http/cart.http
src/controllers/cart.controller.ts
src/repositories/cart.repository.ts
src/services/cart.service.ts

refactor: cart 조회 시 쿼리 이름 수정 [이태빈]

---

src/controllers/cart.controller.ts

- 프론트에서 필요한 응답대로 백엔드 장바구니 조회 응답을 수정했습니다.
-
-

refactor: 장바구니 조회 응답 수정 [이태빈]

---

src/routes/invite.route.ts

refactor: 초대 엔드포인트에 인증 추가 [이태빈]

---

prisma/migrations/20250728042151_add_order_company_id_product_cumulative_sales/migration.sql
prisma/schema.prisma

chore: 스키마 수정 [이태빈]

---

prisma/migrations/20250728050056_init_cumulative_sales_default/migration.sql
prisma/schema.prisma
src/controllers/order.controller.ts
src/repositories/order.repository.ts
src/services/order.service.ts
src/types/product.types.ts

chore: 스키마 수정 및 타입 오류 해결 [이태빈]

---

prisma/mocks/product.mock.ts

product 목데이터 수정 [이태빈]

---

prisma/mocks/cart-item.mock.ts

fix: cartItem 목데이터 수정 [이태빈]

---

http/favorite.http
prisma/migrations/20250731011640_add_unique_constrant_in_like_table/migration.sql
prisma/schema.prisma
src/controllers/favorite.controller.ts
src/repositories/favorite.repository.ts
src/routes/favorite.route.ts
src/routes/index.route.ts
src/services/favorite.service.ts
src/types/favorite.types.ts

feat: 좋아요 기능 추가 [이태빈]

---

src/repositories/favorite.repository.ts
src/services/favorite.service.ts

feat: 찜 목록 조회 응답 수정 [이태빈]

---

http/order.http
src/controllers/order.controller.ts
src/dtos/order.dto.ts
src/repositories/order.repository.ts
src/services/order.service.ts
src/types/order.types.ts

- order 쿼리스트링 수정(offset -> page) 했습니다.
- 쿼리스트링으로 offset을 받았던 것을 page로 받게끔 수정했습니다.
- offset=0을 줘야 1페이지가 나왔었던 로직을 page=1로 받게 되면 1페이지가 나오게끔 내부 로직 수정했습니다.
-

refactor: order 쿼리스트링 수정(offset -> page) [이태빈]

---

http/favorite.http
src/controllers/favorite.controller.ts
src/dtos/favorite.dto.ts
src/repositories/favorite.repository.ts
src/services/favorite.service.ts
src/types/favorite.types.ts

- favorite offset기반 페이지네이션에서 cursor기반 페이지네이션으로 변경
-
-

refactor: favorite offset기반 페이지네이션에서 cursor기반 페이지네이션으로 변경 [이태빈]

---

src/__tests__/sum.test.ts
src/controllers/auth.controller.test.ts
src/controllers/auth.controller.ts
src/controllers/invite.controller.test.ts
src/controllers/invite.controller.ts
src/controllers/user.controller.test.ts
src/controllers/user.controller.ts
src/services/auth.service.test.ts
src/services/invite.service.test.ts
src/services/user.service.test.ts

- 해당 작업의 엔드포인트들 입니다.
- /auth/login
- /auth/signup/:inviteId
- /auth/signup
- /auth/logout
- /auth/refresh-token
- /invite
- /super-admin/users/invite
- 위 엔드포인트들에 대한 controller, service 레이어의 테스트코드와 Swagger api-docs 를 위한 코드 작성했습니다.
- jest 설치 시 테스트를 위해 작성해두었던 `__tests__` 폴더와 sum.test.ts 파일을 삭제
- 위 엔드포인트 들에 대한 Swagger 코드와 테스트 코드 작성 했습니다.
- - jest 설치 시 테스트를 위해 작성해두었던 `__tests__` 폴더와 sum.test.ts 파일을 삭제했습니다.
- npx jest : 전체 테스트 실행
- npx jest --coverage : 커버리지 리포트 확인
- Review는 특수한 …

test: 테스트 코드 작성, Swagger 코드 작성 [김홍섭]

---

package-lock.json
package.json
prisma/migrations/20250803150425_add_payment_table_and_change_order_id_type_uuid/migration.sql
prisma/migrations/20250803194833_add_field_in_payment/migration.sql
prisma/schema.prisma
src/controllers/order.controller.ts
src/repositories/order.repository.ts
src/services/order.service.ts

- 스키마 수정(Payment 테이블 추가, orderId uuid로 변경)
1. 스키마에 결제 승인 정보를 담기 위한 Payment 테이블을 추가
2. 토스 외부 결제 승인 API를 사용하기 위해 orderId를 autoincrement에서 uuid로 형식 변경
-

chore: 스키마 수정(Payment 테이블 추가, orderId uuid로 변경) [이태빈]

---

src/controllers/cart.controller.test.ts
src/controllers/cart.controller.ts
src/services/cart.service.test.ts

- controller, service 레이어의 테스트코드와 Swagger api-docs 를 위한 코드 작성했습니다.
-
-

test:테스트 코드 작성 및 cartAPI swagger 작성 [조성빈]

---

.github/workflows/deploy.yml

- 깃허브 액션 적용을 위한 deploy.yml 파일을 작성했습니다
- 깃허브 액션 적용을 위한 deploy.yml 파일을 작성했습니다
- 이후 자동배포 적용되는지 검토 등

feat: EC2 자동 배포를 위한 GitHub Actions 워크플로우 세팅

---

.github/workflows/deploy.yml

feat: EC2 자동 배포를 위한 GitHub Actions 워크플로우 세팅 deploy.yml 파일 개선(환경변수, 테스트코드 실행 추가)

---

http/tossPayments.http
src/app.ts
src/controllers/payment.controller.ts
src/repositories/payment.repository.ts
src/routes/index.route.ts
src/routes/payment.route.ts
src/services/payment.service.ts

- 토스페이먼츠 결제 모듈 API 연동 및 Payment 로직 추가
1. 토스페이먼트 외부 결제 승인 API 코드 적용
2. 결제 승인 시 필요한 승인 정보를 Payment 테이블에 저장
-

feat: 토스페이먼츠 결제 모듈 API 연동 및 Payment 로직 추가 [이태빈]

---

prisma/seed.ts

- 시딩할때 오류 남
- 존재하지 않는 시퀀스로 인해 오류가 발생하는 줄을 제거
- npm run seed 시 시딩이 잘 됨

fix: 시딩 시 존재하지 않는 시퀀스 참조로 인한 에러 해결 [김홍섭]

---

src/controllers/company.controller.test.ts
src/controllers/company.controller.ts
src/controllers/user.controller.test.ts
src/controllers/user.controller.ts
src/services/company.service.test.ts
src/services/user.service.test.ts

> 해당 작업을 파악하기 위한 개발 계획 문서, 피그마, QA 문서등의 링크를 첨부해주세요
-아래 API에 해당하는 기능 부분 테스트 코드 및 Swagger 주석 작성하였습니다.
아래 API 엔드포인트들에 대한 완전한 테스트 커버리지를 구축했습니다:
- `DELETE /users/:userId` - 회원 탈퇴
- `PATCH /users/:userId/role` - 회원 권한 수정  
-  `GET /users` - 최고관리자의 회사 유저목록 조회
- `PATCH /users/:userId/company` - 회사명, 최고관리자 비밀번호 수정
-  `PATCH /:userId/password` - 유저 비밀번호 수정
-  `GET /:userId/` - 유저 정보 조회
모든 엔드포인트에 대한 상세한 Swagger 주석을 추가했습니다:
-  `GET /users/{userId}` - 유저 정보 조회
-  `DELETE /super-admin/users/{userId}` - (최고관리자) 유저 삭제
-  `PATCH /super-admin/users/{userId}/role` - (최고관리자) 유저 권한 수정
-  `PATCH /users/{userId}/password` - 유저 비밀번호 수정
-  `GET /super-admin/users` - (최고관리자) 회사 유저 목록 조회
-  `PATCH …

feat: 최고관리자 관련 API Test 코드 작성 & Swagger 주석 추가 [이지수B]

---

http/auth.http
http/user/user.company.http
prisma/mocks/receipt.mock.ts
prisma/seed.ts

- 스키마 변경 이후 receipt 목데이터가 order 목데이터에 제대로 연결되지 않아 이슈가 있었습니다. 개선하였습니다.
-
-

refactor: receipt mock 데이터 변경, 시드파일 업데이트 [이지수B]

---

http/order.http
src/controllers/product.controller.ts

fix: 스웨거 오류 잡음 [김우주]

---

src/controllers/invite.controller.ts
src/dtos/invite.dto.ts
src/repositories/invite.repository.ts
src/routes/invite.route.ts
src/services/invite.service.ts

- 한 파일로 뭉쳐져있는 코드를 MVC패턴에 따라 분리
- 한 파일로 뭉쳐져있는 코드를 MVC패턴에 따라 분리했습니다
- `npm test -- --testPathPatterns=invite` 입력으로 invite 관련 API동작, 에러 및 예외 처리, 비즈니스 로직 분리가 제대로 되어있는지 검사합니다.

QA: route 비즈니스 로직 controller/service/repository로 분리 [김홍섭]

---

src/controllers/company.controller.test.ts
src/services/company.service.test.ts

- 테스트 코드에 타입에러 나는거 해결하였습니다
-
-

fix: test code 타입에러 수정 [이지수B]

---

src/routes/payment.route.ts

refactor: 테스트 코드 삭제 [이태빈]

---

src/controllers/payment.controller.ts

feat: 결제 모듈 오류 해결 [이태빈]

---

src/controllers/auth.controller.ts

refactor: 로그인 쿠키 도메인 설정 [이태빈]

---

http/payment.http

test: CI/CD 테스트 [이태빈]

---

src/controllers/auth.controller.test.ts
src/controllers/auth.controller.ts
src/controllers/invite.controller.ts
src/controllers/user.controller.ts
src/routes/auth.route.ts
src/services/auth.service.test.ts
src/services/auth.service.ts

- https://github.com/De-cal/6-Snack-BE/issues/134
- 해당 이슈에서 발견된 컨벤션 관련 이슈를 개선했습니다
- swagger 문서화 코드를 소폭 개선하였습니다
<details>
<summary>전후 비교 및 변경사항 진단 내용</summary>
각 파일의 "전(before)"과 "후(after)"를 비교하면, **로직상 완전히 동일하며, 함수 선언 방식, 코드 형식, 줄바꿈, 주석 등만 변경된 것**으로 진단할 수 있습니다.
아래는 주요 변경 패턴과 진단 내용입니다.
---
- 기존에는 `export class AuthController` 또는 `export class AuthService`와 같이 클래스로 선언되어 있던 것을
- 변경 후에는 각각의 함수를 `const 함수명 = async (...) => {...}`로 선언하고 마지막에 객체로 **export default { ... }** 형태로 내보내는 방식으로 바뀌었습니다.
- 즉, 클래스의 정적(static) 메서드 → 일반 함수 + 객체로 묶음.
**→ 진단:**  
클래스의 정적 메서드는 독립적 함수와 로직적으로 동일하게 동작합니다.  
내부 로직(함수 내용)은 변경되지 않았으며, export/export …

refactor: 맡은 엔드포인트 관련 파일 컨벤션 일관화, swagger 문서화 코드 소폭  [김홍섭]

---

src/services/auth.service.ts

- 회원탈퇴된 사용자는 로그인되지 않게 로직 수정 필요
- 회원탈퇴된 사용자는 차단하고 로그인하지 못하게 서비스로직 수정했습니다.
- npm run test로 백엔드 테스트 진행가능합니다

feat: 회원탈퇴된 사용자 로그인 차단 로직 추가 (auth.service) [김홍섭]

---

src/controllers/favorite.controller.ts
src/controllers/order.controller.ts
src/routes/adminOrder.route.ts

rafactor: 스웨거 최종 수정 [이태빈]

---

src/routes/invite.route.ts
src/routes/my.route.ts

- invite.route와 my.route 두 라우트에 GET은 cacheMiddleware(), 이외 CUD에 해당하는 라우트는 invalidateCache() 적용했습니다.
- 캐싱미들웨어를 Token검사미들웨어 뒤쪽으로 이동했습니다
- invite.route와 my.route 두 라우트에 GET은 cacheMiddleware(), 이외 CUD에 해당하는 라우트는 invalidateCache() 적용했습니다.
- 캐싱미들웨어를 Token검사미들웨어 뒤쪽으로 이동했습니다
- REST Client로 요청 시 속도가 빨라진 것을 확인할 수 있습니다
- 캐싱미들웨어를 Token검사미들웨어 뒤쪽으로 이동했습니다
- Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 …

feat: invite, my API 라우트에 Redis 캐시미들웨어 적용; 캐싱미들웨어를 Token검사미들웨어 뒤쪽으로 이동 [김홍섭]

---

src/routes/product.route.ts
src/routes/superAdmin.route.ts

product, superAdmin 라우트에 redis 추가
product, superAdmin 라우트에 redis 추가
-

product, superAdmin 라우트에 redis 추가 [조성빈]

---

src/routes/admin.route.ts
src/routes/adminOrder.route.ts
src/routes/user.route.ts

feat: Redis 적용 [이태빈]

---

src/routes/order.route.ts
src/routes/payment.route.ts

refactor: order,payment 라우트 수정 [김우주]

---

src/controllers/company.controller.ts
src/controllers/user.controller.ts

refactor: 스웨거 태그 수정 [이지수B]

---

src/config/swagger.ts
src/controllers/auth.controller.ts
src/controllers/budget.controller.ts
src/controllers/cart.controller.ts
src/controllers/company.controller.ts
src/controllers/favorite.controller.ts
src/controllers/invite.controller.ts
src/controllers/order.controller.ts
src/controllers/product.controller.ts
src/controllers/user.controller.ts

refactor: 스웨거 변경 [김우주]

---

src/controllers/user.controller.ts
src/integration-test/user.integration.test.ts
src/middlewares/cacheMiddleware.ts
src/routes/superAdmin.route.ts
src/services/user.service.ts

feat: cacheMiddleware 임시 로그 추가 [이지수B]

---

src/middlewares/cacheMiddleware.ts
src/routes/admin.route.ts
src/routes/adminOrder.route.ts
src/routes/cart.route.ts
src/routes/favorite.route.ts
src/routes/invite.route.ts
src/routes/my.route.ts
src/routes/order.route.ts
src/routes/payment.route.ts
src/routes/product.route.ts
src/routes/superAdmin.route.ts
src/routes/user.route.ts

feat: 레디스 최종 수정 [이태빈]

---

.github/workflows/deploy.yml
src/integration-test/favorite.integration.test.ts
src/routes/superAdmin.route.ts

fix: CI/CD 디버깅 [이태빈]

---

.github/workflows/deploy.yml
src/routes/auth.route.ts

feat: cache 수정 [이태빈]

---

src/controllers/payment.controller.test.ts

fix: 페이먼트 테스트 코드 수정[김우주]

---

src/controllers/auth.controller.test.ts
src/integration-test/budget.integration.test.ts

- Auth 서비스 테스트 PASS
- Auth 컨트롤러 테스트 PASS
- Budget 서비스 테스트 PASS
- Budget 컨트롤러 테스트 PASS
- Budget 통합 테스트 PASS
- Auth 서비스 테스트
- Auth 컨트롤러 테스트
- Budget 서비스 테스트
- Budget 컨트롤러 테스트
- Budget 통합 테스트
- npm run test 로 테스트 가능합니다
- P3 : 이런 방법도 …

test: auth, budgets 테스트코드 개선 및 PASS 확인 [김홍섭]

---

jest.config.js
package.json

- Github Actions에서 jest 코드 실행시 오류나는 문제 해결 위해 jest.config와 package.json 수정하였습니다.
-
-

chore: Jest 설정 변경 [이지수B]

---

.github/workflows/deploy.yml

test: ci/cd 테스트용 DB 마이그레이션 및 시딩 동작 추가
test: ci/cd 테스트용 DB 마이그레이션 및 시딩 동작 추가
- 깃헙 액션스 콘솔로그 참고 부탁드립니다

test: ci/cd 테스트용 DB 마이그레이션 및 시딩 동작 추가 [김홍섭]

---

README.md
prisma/mocks/product.mock.ts

release: main으로 머지(목데이터 수정)
